### ISSUE TITLE
Issue-3

### ISSUE THREAD

**Issue by dagshak** [nyu-cds/ark520_assignment3#3]
In the function definition as well as the function call to _**report_energy**_ in lines 130 and 183,  the assignment of **BODIES=BODIES** is redundant. By doing this, you are making two copies of the reference to the BODIES dictionary object.  
Instead, you can just do one of the below changes
1) Using just BODIES in both these functions will 
    (i) pass a reference to the global BODIES object in the function call
    (ii) receive a reference to the global BODIES object in the function definition 

2) Do the BODIES assignment in the function definition argument list only and NOT pass anything corresponding to BODIES in the function call.  In fact, this is what you have done for the function 
 **_nbody_** in line 198.

All these make shallow copy of the BODIES dictionary. If you want to do the deep copy, you can use **copy.deepcopy(BODIES)**

**Comment by drewkunas** [comment]
Great catch.  I do want to check that we both agree that a **shallow** copy is in fact the desired thing here, right?

This is a **shallow** copy, which has the desired behavior.
```
d = dict()
print("Before: %s" % d)
def f(d=d):
    d['test'] = 'here'
    return
f()
print("After: %s" % d)
```
Prints:

```
Before: {}
After: {'test': 'here'}
```

**Comment by drewkunas** [comment]
Fixed!
