### ISSUE TITLE
Issue-4

### ISSUE THREAD

**Issue by dagshak** [nyu-cds/ark520_assignment3#4]
In **to_do** function, the naming of the variables **thing_for_v1** and **thing_for_v2** doesn't follow the naming convention. You could use something like **body1_velocity_arg** and **body2_velocity_arg**.
OR if you have a better name that convey more information about that variable, you can use that instead.

**Comment by drewkunas** [comment]
Fixed!  I sure wish I knew any physics whatsoever.
